### ISSUE TITLE
Reduce compiler verbosity when compiling code with Expecty

### ISSUE THREAD

**Issue by emchristiansen** [pniederw/expecty#1]
First off, Expecty is great. I've converted 90% of my assertions to Expecty calls. Thanks!

Using SBT and building a project with Expecty, the compiler prints an AST for each call site where Expecty is used. This makes it hard to find useful compiler messages buried in the noise.

If there's some standard trick to make this stuff go away, please mention it on the main page. Otherwise, please modify Expecty so it has a quiet mode.

**Comment by pniederw** [comment]
Thanks for the feedback. You are right, this output shouldn't be shown by default.

**Comment by pniederw** [comment]
Apparently, some environments show compiler info logging by default, and there is no compiler debug log level (at least not for macros). To solve this problem, I've introduced an `org.expecty.debug` system property, which needs to be set to `true` for AST logging to occur. This is now available in the fresh Expecty 0.10 release. Anyway, thanks for the pull request!

**Comment by ephemerist** [comment]
I'm still seeing logging for "RangePosition found!" in expecty 0.10. Could that one be made conditional on the debug property too?

**Comment by emchristiansen** [comment]
I'm also seeing "RangePosition found!".

**Comment by pniederw** [comment]
Sure thing. Mind to open another issue or send a pull request?
